INSERT INTO ACCOUNT(ACCOUNT_NAME, BALANCE, CREATE_DATE) VALUES('Daffy Duck', 0.0, SYSDATE);
INSERT INTO ACCOUNT(ACCOUNT_NAME, BALANCE, CREATE_DATE) VALUES('Elmer Fudd', 0.0, SYSDATE);
INSERT INTO ACCOUNT(ACCOUNT_NAME, BALANCE, CREATE_DATE) VALUES('Wile E. Coyote', 0.0, SYSDATE);